#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : spandsp
Version  : 0.0.6
Release  : 2
URL      : https://www.soft-switch.org/downloads/spandsp/spandsp-0.0.6.tar.gz
Source0  : https://www.soft-switch.org/downloads/spandsp/spandsp-0.0.6.tar.gz
Summary  : A DSP library for telephony.
Group    : Development/Tools
License  : GPL-2.0 LGPL-2.1
Requires: spandsp-lib
BuildRequires : libjpeg-turbo-dev
BuildRequires : libpcap-dev
BuildRequires : pkgconfig(libtiff-4)

%description
SpanDSP is a library of DSP functions for telephony, in the 8000
sample per second world of E1s, T1s, and higher order PCM channels. It
contains low level functions, such as basic filters. It also contains
higher level functions, such as cadenced supervisory tone detection,
and a complete software FAX machine. The software has been designed to
avoid intellectual property issues, using mature techniques where all
relevant patents have expired. See the file DueDiligence for important
information about these intellectual property issues.

%package dev
Summary: dev components for the spandsp package.
Group: Development
Requires: spandsp-lib
Provides: spandsp-devel

%description dev
dev components for the spandsp package.


%package lib
Summary: lib components for the spandsp package.
Group: Libraries

%description lib
lib components for the spandsp package.


%prep
%setup -q -n spandsp-0.0.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525283589
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1525283589
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/spandsp/ademco_contactid.h
/usr/include/spandsp/adsi.h
/usr/include/spandsp/arctan2.h
/usr/include/spandsp/async.h
/usr/include/spandsp/at_interpreter.h
/usr/include/spandsp/awgn.h
/usr/include/spandsp/bell_r2_mf.h
/usr/include/spandsp/bert.h
/usr/include/spandsp/biquad.h
/usr/include/spandsp/bit_operations.h
/usr/include/spandsp/bitstream.h
/usr/include/spandsp/complex.h
/usr/include/spandsp/complex_filters.h
/usr/include/spandsp/complex_vector_float.h
/usr/include/spandsp/complex_vector_int.h
/usr/include/spandsp/crc.h
/usr/include/spandsp/dc_restore.h
/usr/include/spandsp/dds.h
/usr/include/spandsp/dtmf.h
/usr/include/spandsp/echo.h
/usr/include/spandsp/expose.h
/usr/include/spandsp/fast_convert.h
/usr/include/spandsp/fax.h
/usr/include/spandsp/fax_modems.h
/usr/include/spandsp/fir.h
/usr/include/spandsp/fsk.h
/usr/include/spandsp/g168models.h
/usr/include/spandsp/g711.h
/usr/include/spandsp/g722.h
/usr/include/spandsp/g726.h
/usr/include/spandsp/gsm0610.h
/usr/include/spandsp/hdlc.h
/usr/include/spandsp/ima_adpcm.h
/usr/include/spandsp/image_translate.h
/usr/include/spandsp/logging.h
/usr/include/spandsp/lpc10.h
/usr/include/spandsp/math_fixed.h
/usr/include/spandsp/modem_connect_tones.h
/usr/include/spandsp/modem_echo.h
/usr/include/spandsp/noise.h
/usr/include/spandsp/oki_adpcm.h
/usr/include/spandsp/playout.h
/usr/include/spandsp/plc.h
/usr/include/spandsp/power_meter.h
/usr/include/spandsp/private/ademco_contactid.h
/usr/include/spandsp/private/adsi.h
/usr/include/spandsp/private/async.h
/usr/include/spandsp/private/at_interpreter.h
/usr/include/spandsp/private/awgn.h
/usr/include/spandsp/private/bell_r2_mf.h
/usr/include/spandsp/private/bert.h
/usr/include/spandsp/private/bitstream.h
/usr/include/spandsp/private/dtmf.h
/usr/include/spandsp/private/echo.h
/usr/include/spandsp/private/fax.h
/usr/include/spandsp/private/fax_modems.h
/usr/include/spandsp/private/fsk.h
/usr/include/spandsp/private/g711.h
/usr/include/spandsp/private/g722.h
/usr/include/spandsp/private/g726.h
/usr/include/spandsp/private/gsm0610.h
/usr/include/spandsp/private/hdlc.h
/usr/include/spandsp/private/ima_adpcm.h
/usr/include/spandsp/private/image_translate.h
/usr/include/spandsp/private/logging.h
/usr/include/spandsp/private/lpc10.h
/usr/include/spandsp/private/modem_connect_tones.h
/usr/include/spandsp/private/modem_echo.h
/usr/include/spandsp/private/noise.h
/usr/include/spandsp/private/oki_adpcm.h
/usr/include/spandsp/private/queue.h
/usr/include/spandsp/private/schedule.h
/usr/include/spandsp/private/sig_tone.h
/usr/include/spandsp/private/silence_gen.h
/usr/include/spandsp/private/super_tone_rx.h
/usr/include/spandsp/private/super_tone_tx.h
/usr/include/spandsp/private/swept_tone.h
/usr/include/spandsp/private/t30.h
/usr/include/spandsp/private/t30_dis_dtc_dcs_bits.h
/usr/include/spandsp/private/t31.h
/usr/include/spandsp/private/t38_core.h
/usr/include/spandsp/private/t38_gateway.h
/usr/include/spandsp/private/t38_non_ecm_buffer.h
/usr/include/spandsp/private/t38_terminal.h
/usr/include/spandsp/private/t4_rx.h
/usr/include/spandsp/private/t4_t6_decode.h
/usr/include/spandsp/private/t4_t6_encode.h
/usr/include/spandsp/private/t4_tx.h
/usr/include/spandsp/private/time_scale.h
/usr/include/spandsp/private/timezone.h
/usr/include/spandsp/private/tone_detect.h
/usr/include/spandsp/private/tone_generate.h
/usr/include/spandsp/private/v17rx.h
/usr/include/spandsp/private/v17tx.h
/usr/include/spandsp/private/v18.h
/usr/include/spandsp/private/v22bis.h
/usr/include/spandsp/private/v27ter_rx.h
/usr/include/spandsp/private/v27ter_tx.h
/usr/include/spandsp/private/v29rx.h
/usr/include/spandsp/private/v29tx.h
/usr/include/spandsp/private/v42.h
/usr/include/spandsp/private/v42bis.h
/usr/include/spandsp/private/v8.h
/usr/include/spandsp/queue.h
/usr/include/spandsp/saturated.h
/usr/include/spandsp/schedule.h
/usr/include/spandsp/sig_tone.h
/usr/include/spandsp/silence_gen.h
/usr/include/spandsp/stdbool.h
/usr/include/spandsp/super_tone_rx.h
/usr/include/spandsp/super_tone_tx.h
/usr/include/spandsp/swept_tone.h
/usr/include/spandsp/t30.h
/usr/include/spandsp/t30_api.h
/usr/include/spandsp/t30_fcf.h
/usr/include/spandsp/t30_logging.h
/usr/include/spandsp/t31.h
/usr/include/spandsp/t35.h
/usr/include/spandsp/t38_core.h
/usr/include/spandsp/t38_gateway.h
/usr/include/spandsp/t38_non_ecm_buffer.h
/usr/include/spandsp/t38_terminal.h
/usr/include/spandsp/t4_rx.h
/usr/include/spandsp/t4_t6_decode.h
/usr/include/spandsp/t4_t6_encode.h
/usr/include/spandsp/t4_tx.h
/usr/include/spandsp/telephony.h
/usr/include/spandsp/time_scale.h
/usr/include/spandsp/timezone.h
/usr/include/spandsp/timing.h
/usr/include/spandsp/tone_detect.h
/usr/include/spandsp/tone_generate.h
/usr/include/spandsp/v17rx.h
/usr/include/spandsp/v17tx.h
/usr/include/spandsp/v18.h
/usr/include/spandsp/v22bis.h
/usr/include/spandsp/v27ter_rx.h
/usr/include/spandsp/v27ter_tx.h
/usr/include/spandsp/v29rx.h
/usr/include/spandsp/v29tx.h
/usr/include/spandsp/v42.h
/usr/include/spandsp/v42bis.h
/usr/include/spandsp/v8.h
/usr/include/spandsp/vector_float.h
/usr/include/spandsp/vector_int.h
/usr/include/spandsp/version.h
/usr/lib64/libspandsp.so
/usr/lib64/pkgconfig/spandsp.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libspandsp.so.2
/usr/lib64/libspandsp.so.2.0.0
